### ISSUE TITLE
Difficulties detecting (or ignoring!) middle finger pinching

### ISSUE THREAD

**Issue by aidanhs** [handtracking-io/yoha#8]
When playing around with the demo, I observed that it does really well for detecting index finger pinching, but struggles with middle finger pinching - to the point where I'm not even sure if it's intended to draw with middle finger pinching or not!

The video is a nice demo of the issue, but just generally if you move your hand while playing with middle-finger pinch I saw a lot of oddities and inconsistencies.

https://user-images.githubusercontent.com/1050652/137144907-9f52cbe0-f417-464b-a048-79fba116c8bf.mp4

**Comment by b-3-n** [comment]
Thank you for the detailed issue. This is expected behavior right now. I updated the README file with a more precise description of the pinch hand pose i.e. that index finger and thumb touch.

If you'd like other pinch poses (or other poses in general) to be supported please create a GitHub issue. There is a specific issue template for requesting new hand poses that you can select when opening a new issue.
